from . import member_application
from . import member_application_child
from . import member_application_document
from . import member_application_boat
from . import member_application_other_membership
from . import res_partner
from . import res_partner_child
from . import res_partner_document
from . import res_partner_boat
from . import res_partner_other_membership